version: '3.4'

services:

    postgres:
        image: postgres

        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=my_db
#        ports:
#            - "5433:5432"
        volumes:
            - ./tmp/lib:/var/lib/postgresql/10/main
            - ./tmp/log:/var/log/postgresql
            - ./tmp/etc:/etc/postgresql

        restart: always


    node:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
            args:
                server_uid: 1000
        ports:
            - "5000:5000"
        volumes:
            - ./www/:/web/www
            - /etc/localtime:/etc/localtime/:ro
        command: "sudo -u node bash /scripts/start.sh"
        restart: always
